// GENERATED by `pnpm corpus:verify`. Do not edit by hand.
//
// Which detection rules a REAL captured block page has confirmed, and what proves it.
//
// This used to be a boolean on each rule. It was false on all six, which was honest, and it was
// also a value anyone could set to true with no capture behind it — while the website read it and
// printed "no real capture yet" to visitors. A claim that load-bearing should not be typeable.
//
// A rule appears here only because a stored capture, run through the real `detect()`, fired that
// exact rule. `digests` are SHA-256 prefixes of the captured bytes, so each claim names an
// artefact. `classes` are kinds of target, never hostnames — `plan.md` section 19.
//
// The captures themselves are mostly NOT in this repository, for the same reason. CI cannot
// regenerate this file and does not try; `repo:check` holds it to naming real rules and citing a
// digest for every claim, and a maintainer with the corpus runs `pnpm corpus:verify --write`.

export interface VerifiedRule {
	/** How many stored captures fired this rule. */
	readonly captures: number;
	/** Kinds of target it was seen on. Never a hostname. */
	readonly classes: readonly string[];
	readonly lastVerified: string;
	/** SHA-256 prefixes of the captured bytes, so the claim points at an artefact. */
	readonly digests: readonly string[];
}

export const VERIFIED: Readonly<Record<string, VerifiedRule>> = {
	'akamai-bot-manager': {
		captures: 1,
		classes: ['retail'],
		lastVerified: '2026-08-21',
		digests: ['05659c252ee5b2dc'],
	},
	'cloudflare-blocked': {
		captures: 1,
		classes: ['publishing'],
		lastVerified: '2026-08-21',
		digests: ['bbd2447ddb2faaf8'],
	},
	'cloudflare-challenge': {
		captures: 2,
		classes: ['bot-test-page', 'business-data'],
		lastVerified: '2026-08-21',
		digests: ['61c20be6f1cf1cbe', '75915405343a92b9'],
	},
	datadome: {
		captures: 1,
		classes: ['bot-vendor-site'],
		lastVerified: '2026-08-21',
		digests: ['6a89f93e9da83547'],
	},
	perimeterx: {
		captures: 1,
		classes: ['property-listings'],
		lastVerified: '2026-08-21',
		digests: ['d74ab27907bd9761'],
	},
};
