/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsAdaptersRouteImport } from './routes/docs/adapters'
import { Route as DocsAgentsRouteImport } from './routes/docs/agents'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as DocsChangelogRouteImport } from './routes/docs/changelog'
import { Route as DocsFailoverRouteImport } from './routes/docs/failover'
import { Route as DocsFaqRouteImport } from './routes/docs/faq'
import { Route as DocsHostingRouteImport } from './routes/docs/hosting'
import { Route as DocsOutcomesRouteImport } from './routes/docs/outcomes'
import { Route as DocsQuickstartRouteImport } from './routes/docs/quickstart'
import { Route as DocsUseCasesRouteImport } from './routes/docs/use-cases'
import { Route as Symptoms200CaptchaBodyRouteImport } from './routes/symptoms/200-captcha-body'
import { Route as Symptoms403WhileScrapingRouteImport } from './routes/symptoms/403-while-scraping'
import { Route as SymptomsCloudflareChallengePlaywrightRouteImport } from './routes/symptoms/cloudflare-challenge-playwright'
import { Route as SymptomsDatadomeDetectionRouteImport } from './routes/symptoms/datadome-detection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAdaptersRoute = DocsAdaptersRouteImport.update({
  id: '/docs/adapters',
  path: '/docs/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsAgentsRoute = DocsAgentsRouteImport.update({
  id: '/docs/agents',
  path: '/docs/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChangelogRoute = DocsChangelogRouteImport.update({
  id: '/docs/changelog',
  path: '/docs/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFailoverRoute = DocsFailoverRouteImport.update({
  id: '/docs/failover',
  path: '/docs/failover',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsFaqRoute = DocsFaqRouteImport.update({
  id: '/docs/faq',
  path: '/docs/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHostingRoute = DocsHostingRouteImport.update({
  id: '/docs/hosting',
  path: '/docs/hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsOutcomesRoute = DocsOutcomesRouteImport.update({
  id: '/docs/outcomes',
  path: '/docs/outcomes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/docs/quickstart',
  path: '/docs/quickstart',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsUseCasesRoute = DocsUseCasesRouteImport.update({
  id: '/docs/use-cases',
  path: '/docs/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const Symptoms200CaptchaBodyRoute = Symptoms200CaptchaBodyRouteImport.update({
  id: '/symptoms/200-captcha-body',
  path: '/symptoms/200-captcha-body',
  getParentRoute: () => rootRouteImport,
} as any)
const Symptoms403WhileScrapingRoute =
  Symptoms403WhileScrapingRouteImport.update({
    id: '/symptoms/403-while-scraping',
    path: '/symptoms/403-while-scraping',
    getParentRoute: () => rootRouteImport,
  } as any)
const SymptomsCloudflareChallengePlaywrightRoute =
  SymptomsCloudflareChallengePlaywrightRouteImport.update({
    id: '/symptoms/cloudflare-challenge-playwright',
    path: '/symptoms/cloudflare-challenge-playwright',
    getParentRoute: () => rootRouteImport,
  } as any)
const SymptomsDatadomeDetectionRoute =
  SymptomsDatadomeDetectionRouteImport.update({
    id: '/symptoms/datadome-detection',
    path: '/symptoms/datadome-detection',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/adapters': typeof DocsAdaptersRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/failover': typeof DocsFailoverRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/hosting': typeof DocsHostingRoute
  '/docs/outcomes': typeof DocsOutcomesRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/use-cases': typeof DocsUseCasesRoute
  '/symptoms/200-captcha-body': typeof Symptoms200CaptchaBodyRoute
  '/symptoms/403-while-scraping': typeof Symptoms403WhileScrapingRoute
  '/symptoms/cloudflare-challenge-playwright': typeof SymptomsCloudflareChallengePlaywrightRoute
  '/symptoms/datadome-detection': typeof SymptomsDatadomeDetectionRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/adapters': typeof DocsAdaptersRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/failover': typeof DocsFailoverRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/hosting': typeof DocsHostingRoute
  '/docs/outcomes': typeof DocsOutcomesRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/use-cases': typeof DocsUseCasesRoute
  '/symptoms/200-captcha-body': typeof Symptoms200CaptchaBodyRoute
  '/symptoms/403-while-scraping': typeof Symptoms403WhileScrapingRoute
  '/symptoms/cloudflare-challenge-playwright': typeof SymptomsCloudflareChallengePlaywrightRoute
  '/symptoms/datadome-detection': typeof SymptomsDatadomeDetectionRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/adapters': typeof DocsAdaptersRoute
  '/docs/agents': typeof DocsAgentsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/docs/failover': typeof DocsFailoverRoute
  '/docs/faq': typeof DocsFaqRoute
  '/docs/hosting': typeof DocsHostingRoute
  '/docs/outcomes': typeof DocsOutcomesRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/use-cases': typeof DocsUseCasesRoute
  '/symptoms/200-captcha-body': typeof Symptoms200CaptchaBodyRoute
  '/symptoms/403-while-scraping': typeof Symptoms403WhileScrapingRoute
  '/symptoms/cloudflare-challenge-playwright': typeof SymptomsCloudflareChallengePlaywrightRoute
  '/symptoms/datadome-detection': typeof SymptomsDatadomeDetectionRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/adapters'
    | '/docs/agents'
    | '/docs/api'
    | '/docs/changelog'
    | '/docs/failover'
    | '/docs/faq'
    | '/docs/hosting'
    | '/docs/outcomes'
    | '/docs/quickstart'
    | '/docs/use-cases'
    | '/symptoms/200-captcha-body'
    | '/symptoms/403-while-scraping'
    | '/symptoms/cloudflare-challenge-playwright'
    | '/symptoms/datadome-detection'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/adapters'
    | '/docs/agents'
    | '/docs/api'
    | '/docs/changelog'
    | '/docs/failover'
    | '/docs/faq'
    | '/docs/hosting'
    | '/docs/outcomes'
    | '/docs/quickstart'
    | '/docs/use-cases'
    | '/symptoms/200-captcha-body'
    | '/symptoms/403-while-scraping'
    | '/symptoms/cloudflare-challenge-playwright'
    | '/symptoms/datadome-detection'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs/adapters'
    | '/docs/agents'
    | '/docs/api'
    | '/docs/changelog'
    | '/docs/failover'
    | '/docs/faq'
    | '/docs/hosting'
    | '/docs/outcomes'
    | '/docs/quickstart'
    | '/docs/use-cases'
    | '/symptoms/200-captcha-body'
    | '/symptoms/403-while-scraping'
    | '/symptoms/cloudflare-challenge-playwright'
    | '/symptoms/datadome-detection'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsAdaptersRoute: typeof DocsAdaptersRoute
  DocsAgentsRoute: typeof DocsAgentsRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsChangelogRoute: typeof DocsChangelogRoute
  DocsFailoverRoute: typeof DocsFailoverRoute
  DocsFaqRoute: typeof DocsFaqRoute
  DocsHostingRoute: typeof DocsHostingRoute
  DocsOutcomesRoute: typeof DocsOutcomesRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsUseCasesRoute: typeof DocsUseCasesRoute
  Symptoms200CaptchaBodyRoute: typeof Symptoms200CaptchaBodyRoute
  Symptoms403WhileScrapingRoute: typeof Symptoms403WhileScrapingRoute
  SymptomsCloudflareChallengePlaywrightRoute: typeof SymptomsCloudflareChallengePlaywrightRoute
  SymptomsDatadomeDetectionRoute: typeof SymptomsDatadomeDetectionRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/adapters': {
      id: '/docs/adapters'
      path: '/docs/adapters'
      fullPath: '/docs/adapters'
      preLoaderRoute: typeof DocsAdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/agents': {
      id: '/docs/agents'
      path: '/docs/agents'
      fullPath: '/docs/agents'
      preLoaderRoute: typeof DocsAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/changelog': {
      id: '/docs/changelog'
      path: '/docs/changelog'
      fullPath: '/docs/changelog'
      preLoaderRoute: typeof DocsChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/failover': {
      id: '/docs/failover'
      path: '/docs/failover'
      fullPath: '/docs/failover'
      preLoaderRoute: typeof DocsFailoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/faq': {
      id: '/docs/faq'
      path: '/docs/faq'
      fullPath: '/docs/faq'
      preLoaderRoute: typeof DocsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/hosting': {
      id: '/docs/hosting'
      path: '/docs/hosting'
      fullPath: '/docs/hosting'
      preLoaderRoute: typeof DocsHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/outcomes': {
      id: '/docs/outcomes'
      path: '/docs/outcomes'
      fullPath: '/docs/outcomes'
      preLoaderRoute: typeof DocsOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/docs/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/use-cases': {
      id: '/docs/use-cases'
      path: '/docs/use-cases'
      fullPath: '/docs/use-cases'
      preLoaderRoute: typeof DocsUseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms/200-captcha-body': {
      id: '/symptoms/200-captcha-body'
      path: '/symptoms/200-captcha-body'
      fullPath: '/symptoms/200-captcha-body'
      preLoaderRoute: typeof Symptoms200CaptchaBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms/403-while-scraping': {
      id: '/symptoms/403-while-scraping'
      path: '/symptoms/403-while-scraping'
      fullPath: '/symptoms/403-while-scraping'
      preLoaderRoute: typeof Symptoms403WhileScrapingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms/cloudflare-challenge-playwright': {
      id: '/symptoms/cloudflare-challenge-playwright'
      path: '/symptoms/cloudflare-challenge-playwright'
      fullPath: '/symptoms/cloudflare-challenge-playwright'
      preLoaderRoute: typeof SymptomsCloudflareChallengePlaywrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms/datadome-detection': {
      id: '/symptoms/datadome-detection'
      path: '/symptoms/datadome-detection'
      fullPath: '/symptoms/datadome-detection'
      preLoaderRoute: typeof SymptomsDatadomeDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsAdaptersRoute: DocsAdaptersRoute,
  DocsAgentsRoute: DocsAgentsRoute,
  DocsApiRoute: DocsApiRoute,
  DocsChangelogRoute: DocsChangelogRoute,
  DocsFailoverRoute: DocsFailoverRoute,
  DocsFaqRoute: DocsFaqRoute,
  DocsHostingRoute: DocsHostingRoute,
  DocsOutcomesRoute: DocsOutcomesRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsUseCasesRoute: DocsUseCasesRoute,
  Symptoms200CaptchaBodyRoute: Symptoms200CaptchaBodyRoute,
  Symptoms403WhileScrapingRoute: Symptoms403WhileScrapingRoute,
  SymptomsCloudflareChallengePlaywrightRoute:
    SymptomsCloudflareChallengePlaywrightRoute,
  SymptomsDatadomeDetectionRoute: SymptomsDatadomeDetectionRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
