// A regeneration that quietly withdraws claims it cannot currently prove.
//
// `corpus:verify --write` rebuilds `verified.ts` from whatever captures are mounted. It already
// refused to run when `PROXLANE_PRIVATE_CORPUS` was absent entirely, with the right reason
// written down — "the difference between 'not verified' and 'unverifiable from here'".
//
// It did not check the case that actually happens. A corpus that is present but INCOMPLETE — one
// machine holding one of six captures — passed that guard and regenerated the table from what
// was mounted. Measured on 2026-08-29: pointing it at a directory containing a single capture
// rewrote a five-rule table down to one, exit 0, no warning. `apps/web` reads this file and
// prints "no real capture yet" for anything missing, so the visible result is the project
// retracting true claims about itself, in public, from a command whose whole job is honesty.
//
// The captures are deliberately not in the repo (plan.md section 19), which is exactly why a
// partial corpus is the normal state on any given machine rather than an unlikely one.

import { describe, expect, it } from 'vitest';
import { retractions } from '../../scripts/corpus-verify.ts';

/** The shape `render()` emits, which is what the committed file always looks like. */
const committed = `// GENERATED by \`pnpm corpus:verify\`. Do not edit by hand.
export const VERIFIED: Readonly<Record<string, VerifiedRule>> = {
	'akamai-bot-manager': {
		captures: 1,
		classes: ['retail'],
		lastVerified: '2026-08-21',
		digests: ['05659c252ee5b2dc'],
	},
	'cloudflare-challenge': {
		captures: 2,
		classes: ['bot-test-page', 'business-data'],
		lastVerified: '2026-08-21',
		digests: ['61c20be6f1cf1cbe', '75915405343a92b9'],
	},
	datadome: {
		captures: 1,
		classes: ['retail'],
		lastVerified: '2026-08-21',
		digests: ['d74ab27907bd9761'],
	},
};
`;

const rule = (captures: number) => ({
	captures,
	classes: ['x'],
	lastVerified: '2026-08-29',
	digests: ['aaaaaaaaaaaaaaaa'],
});

describe('a regeneration cannot silently withdraw a claim', () => {
	it('names every rule that would disappear', () => {
		// The real failure, reproduced: a corpus holding only the cloudflare capture.
		const gone = retractions(committed, { 'cloudflare-challenge': rule(2) });
		expect(gone).toEqual([
			'akamai-bot-manager (1 capture(s) -> none)',
			'datadome (1 capture(s) -> none)',
		]);
	});

	it('catches a rule that survives with fewer captures behind it', () => {
		// Quieter and worse: the rule stays verified, and the evidence behind it halves without
		// anyone reading a diff closely enough to notice a `2` become a `1`.
		const gone = retractions(committed, {
			'akamai-bot-manager': rule(1),
			'cloudflare-challenge': rule(1),
			datadome: rule(1),
		});
		expect(gone).toEqual(['cloudflare-challenge (2 capture(s) -> 1)']);
	});

	it('is silent when the table only grows', () => {
		// Adding a rule is the ordinary case and must not need a flag, or the guard becomes
		// something people pass `--allow-retractions` to out of habit.
		const gone = retractions(committed, {
			'akamai-bot-manager': rule(1),
			'cloudflare-challenge': rule(2),
			datadome: rule(1),
			'imperva-incapsula': rule(1),
		});
		expect(gone).toEqual([]);
	});

	it('reads both quoted and bare rule keys, which render() emits interchangeably', () => {
		// `datadome` is emitted bare and `'akamai-bot-manager'` quoted, because the generator
		// writes an object literal. A parser that handled only one would under-report exactly the
		// rules whose names happen not to need quoting.
		expect(retractions(committed, {})).toHaveLength(3);
	});
});
