// Generates .github/CODEOWNERS from the ownership table in CLAUDE.md.
//
// The table is the source of truth. If a path has the wrong owner, fix the table — never
// the generated file, which repo:check asserts is byte-identical to a fresh render.
//
// Run:  node scripts/codeowners.ts          # write
//       node scripts/codeowners.ts --check  # exit 1 on drift

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');

/**
 * One mapping constant, and its value is a user rather than a team on purpose.
 *
 * `gh api orgs/proxlane/teams` returns empty, and creating one needs admin:org. A CODEOWNERS
 * naming a team that does not exist is an "Unknown owner" error that GitHub silently
 * ignores — which would leave assertions 3 and 4 both passing on a file that does nothing.
 * Change this to @proxlane/<team> the day a team exists.
 */
export const OWNER = '@scarsam';

export function parseTable(md: string, headingRegex: RegExp): string[][] {
	const lines = md.split('\n');
	const start = lines.findIndex((l) => headingRegex.test(l));
	if (start === -1) return [];
	const rows: string[][] = [];
	let seenDelimiter = false;
	for (let i = start + 1; i < lines.length; i++) {
		const line = lines[i] ?? '';
		if (line.startsWith('#')) break;
		if (!line.trim().startsWith('|')) {
			if (rows.length > 0 || seenDelimiter) {
				if (line.trim() === '') continue;
				break;
			}
			continue;
		}
		const cells = line
			.split('|')
			.slice(1, -1)
			.map((c) => c.trim());
		if (cells.every((c) => /^:?-{2,}:?$/.test(c))) {
			seenDelimiter = true;
			continue;
		}
		if (!seenDelimiter) continue;
		rows.push(cells);
	}
	return rows;
}

export function ticks(cell: string): string[] {
	return [...cell.matchAll(/`([^`]+)`/g)].map((m) => m[1] as string);
}

export function buildCodeowners(md: string): string {
	const rows = parseTable(md, /^\| Path \| What \| Owner \|/);
	const lines = [
		'# GENERATED by scripts/codeowners.ts from the ownership table in CLAUDE.md.',
		'# Do not edit. If a path has the wrong owner, fix the table.',
		'#',
		'# Last match wins, so general rows come before their children — that ordering is',
		'# load-bearing and stated in CLAUDE.md.',
		'#',
		'# Every role maps to the maintainer today; the role is kept as a comment so the',
		'# mapping can become per-team without losing which brief owns the path.',
		'',
	];
	let emitted = 0;
	for (const row of rows) {
		const paths = ticks(row[0] ?? '');
		const role = (row[2] ?? '').replace(/[*`]/g, '').trim();
		if (paths.length === 0 || !role) continue;
		for (const p of paths) {
			lines.push(`${p.padEnd(34)} ${OWNER}   # ${role}`);
			emitted++;
		}
	}
	if (emitted === 0) throw new Error('ownership table produced zero CODEOWNERS lines');
	lines.push('');
	return lines.join('\n');
}

if (import.meta.filename === process.argv[1]) {
	const md = readFileSync(join(ROOT, 'CLAUDE.md'), 'utf8');
	const generated = buildCodeowners(md);
	const target = join(ROOT, '.github/CODEOWNERS');
	if (process.argv.includes('--check')) {
		const current = readFileSync(target, 'utf8');
		if (current !== generated) {
			process.stderr.write('CODEOWNERS is stale — run: node scripts/codeowners.ts\n');
			process.exit(1);
		}
		process.stdout.write('CODEOWNERS is current\n');
	} else {
		mkdirSync(join(ROOT, '.github'), { recursive: true });
		writeFileSync(target, generated);
		process.stdout.write(`wrote .github/CODEOWNERS (${generated.split('\n').length} lines)\n`);
	}
}
