// Regenerate `src/schema/auth.ts` from `src/auth.ts`.
//
// Two steps, and the second one is not a preference.
//
// 1. `auth generate` reads the real `createAuth` factory, so the schema can never drift from
//    the configuration the app builds. The generator is pinned to better-auth's OWN version:
//    `@better-auth/cli` is a different, STALE package — 1.4.21 against better-auth 1.6.27 —
//    and it is the name older docs give, so reaching for it silently generates against a
//    version two minors behind. The live CLI is `auth`.
//
// 2. Every `timestamp` column is rewritten to `timestamptz`. Better Auth's Drizzle codegen
//    emits `timestamp without time zone`, but its own Kysely migrator maps dates to
//    `timestamptz` for Postgres:
//
//      date: { sqlite: "date", postgres: "timestamptz", mysql: "timestamp(3)" }
//                                        ^ better-auth/dist/db/get-migration.mjs
//
//    So the two halves of the same library disagree, and the Drizzle half is the one that is
//    wrong. This is not us overriding upstream; it is us picking the answer upstream already
//    gives when it writes the DDL itself.
//
//    It matters because `session.expiresAt` in local time is a security bug the day the clock
//    shifts, and because a column type is the least reversible thing in a schema. `pnpm test`
//    asserts the invariant, so a regeneration that skips this step fails rather than quietly
//    reintroducing naked timestamps.

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(PKG, 'src/schema/auth.ts');

/** `better-auth` does not export `package.json`, so read it off the resolved entry point. */
function betterAuthVersion(): string {
	const require = createRequire(join(PKG, 'noop.js'));
	const entry = require.resolve('better-auth');
	// …/node_modules/better-auth/dist/index.mjs -> …/node_modules/better-auth/package.json
	const root = entry.slice(0, entry.indexOf(`${'better-auth'}/`) + 'better-auth/'.length);
	const version = (
		JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as {
			version?: string;
		}
	).version;
	if (version === undefined) throw new Error('could not read better-auth version');
	return version;
}

/**
 * `timestamp("x")` -> `timestamp("x", { withTimezone: true })`.
 *
 * Exported so the test can assert the transform is idempotent and total rather than
 * re-implementing the regex and agreeing with itself.
 */
export function withTimezone(source: string): string {
	return source.replace(
		/timestamp\((\s*)"([a-z_]+)"\s*\)/g,
		'timestamp($1"$2", { withTimezone: true })',
	);
}

/** Every timestamp column that is still naked. Empty is the only acceptable answer. */
export function nakedTimestamps(source: string): string[] {
	return [...source.matchAll(/timestamp\(\s*"([a-z_]+)"\s*\)/g)].map((m) => m[1] ?? '');
}

if (import.meta.filename === process.argv[1]) {
	const version = betterAuthVersion();
	process.stdout.write(`  generating against better-auth ${version}\n`);
	execFileSync(
		'pnpm',
		['dlx', `auth@${version}`, 'generate', '--config', 'auth.gen.ts', '--output', OUT, '-y'],
		{ cwd: PKG, stdio: ['ignore', 'inherit', 'inherit'] },
	);

	const raw = readFileSync(OUT, 'utf8');
	const before = nakedTimestamps(raw).length;
	const fixed = withTimezone(raw);
	const after = nakedTimestamps(fixed).length;
	if (after !== 0)
		throw new Error(`${after} timestamp column(s) still naked after the rewrite`);

	writeFileSync(
		OUT,
		`// GENERATED by \`pnpm --filter @proxlane/db codegen:auth\`. Do not edit.\n` +
			`// Source of truth is \`src/auth.ts\`; see \`scripts/generate-auth-schema.ts\` for why\n` +
			`// every timestamp is timestamptz.\n\n${fixed}`,
	);
	process.stdout.write(`  rewrote ${before} timestamp column(s) to timestamptz\n`);
}
